In [27]:
import cv2
import os
import argparse
import numpy as np
import PIL
from PIL import Image
from __future__ import print_function
import time

In [28]:


#Initialize Counter for Bag
count = 0
x = []
#create Background Subtractor objects
backSub = cv2.createBackgroundSubtractorMOG2()    
#Initialize Camera Object
cap = cv2.VideoCapture(r"D:\Images\vid_9.mp4")
while cap.isOpened():
    #Read Video Frame by Frame
    ret, frame = cap.read()
    
    #resize frame change coordinates
    new_size = (500,300)
    frame = cv2.resize(frame, new_size)
#     frame = frame[110:300,40:250]
    
    #Cut Frame to Desired Dimensions
#     frame = frame[300:1000,100:1500]

    #update the background model
    fgMask = backSub.apply(frame)
    
    cv2.rectangle(frame, (10, 2), (100,20), (255,0,0), 1)
    cv2.putText(frame, str(cap.get(cv2.CAP_PROP_POS_FRAMES)), (15, 15),
               cv2.FONT_HERSHEY_SIMPLEX, 0.5 , (0,0,0))
    
    #Convert to Gray Scale First
    grayscale = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    #Now Convert Gray Frame Using Threshold Values to Black and White Frame
    ret, threshold = cv2.threshold(grayscale, 135, 255, cv2.THRESH_BINARY)
    
    # Detect the pattern
    contours, heirarchy = cv2.findContours(threshold, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_TC89_KCOS)
    for cnt in contours:
        (x, y, w, h) = cv2.boundingRect(cnt)
#         list.append(cnt)
        
        # Find Area of the Object Passed
        area = cv2.contourArea(cnt)
        cv2.putText(threshold, str(area), (x, y), 0, 1, (255, 255, 255))
        cv2.rectangle(threshold, (x, y), (x + w, y + h), (255, 0, 0), 1)
        
        #area according to object area passing through frame,
        if 18100 < area:
            print(area)
#             print(len(x))
            count += 1
            print(count)
        
#     #Display Frames
#     cv2.imshow('frame', frame)
#     cv2.imshow('grayscale', grayscale)
    cv2.imshow('threshold', threshold)
    
    #Break Control
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

#Exit Gracefully
cap.release()
cv2.destroyAllWindows()

[[[161 108]]

 [[158 109]]

 [[155 111]]

 [[151 112]]

 [[142 113]]

 [[138 115]]

 [[133 115]]

 [[126 117]]

 [[119 119]]

 [[ 98 126]]

 [[ 90 130]]

 [[ 78 133]]

 [[ 55 143]]

 [[ 44 147]]

 [[ 41 148]]

 [[ 38 149]]

 [[ 31 151]]

 [[ 13 154]]

 [[  4 157]]

 [[  0 159]]

 [[  0 183]]

 [[  4 184]]

 [[  4 190]]

 [[  3 190]]

 [[  1 192]]

 [[  1 195]]

 [[  4 198]]

 [[  7 199]]

 [[ 11 199]]

 [[ 14 201]]

 [[ 18 205]]

 [[ 22 207]]

 [[ 25 210]]

 [[ 27 214]]

 [[ 27 216]]

 [[ 26 221]]

 [[ 34 229]]

 [[ 36 232]]

 [[ 35 228]]

 [[ 37 227]]

 [[ 38 226]]

 [[ 40 226]]

 [[ 43 229]]

 [[ 42 235]]

 [[ 42 237]]

 [[ 44 242]]

 [[ 44 247]]

 [[ 45 250]]

 [[ 49 255]]

 [[ 49 256]]

 [[ 50 257]]

 [[ 52 258]]

 [[ 57 259]]

 [[ 60 262]]

 [[ 59 265]]

 [[ 60 267]]

 [[ 64 271]]

 [[ 68 272]]

 [[ 70 274]]

 [[ 70 284]]

 [[ 71 285]]

 [[ 71 289]]

 [[ 74 288]]

 [[ 74 286]]

 [[ 76 283]]

 [[ 79 280]]

 [[ 82 274]]

 [[ 84 269]]

 [[ 84 263]]

 [[ 85 260]]

 [[ 90 252]]

 [[ 94

[[[161 111]]

 [[156 113]]

 [[150 113]]

 [[145 114]]

 [[132 117]]

 [[128 118]]

 [[124 119]]

 [[106 124]]

 [[ 98 127]]

 [[ 93 130]]

 [[ 90 131]]

 [[ 84 132]]

 [[ 81 133]]

 [[ 76 136]]

 [[ 68 139]]

 [[ 51 145]]

 [[ 45 147]]

 [[ 36 150]]

 [[ 29 152]]

 [[ 25 153]]

 [[ 15 154]]

 [[ 10 155]]

 [[  6 156]]

 [[  4 157]]

 [[  1 159]]

 [[  0 161]]

 [[  0 184]]

 [[  7 184]]

 [[  9 186]]

 [[ 11 191]]

 [[ 10 194]]

 [[  9 194]]

 [[  7 196]]

 [[  7 198]]

 [[  9 200]]

 [[ 12 201]]

 [[ 15 204]]

 [[ 18 205]]

 [[ 21 207]]

 [[ 25 211]]

 [[ 28 215]]

 [[ 29 217]]

 [[ 30 222]]

 [[ 31 224]]

 [[ 34 228]]

 [[ 36 232]]

 [[ 36 236]]

 [[ 37 239]]

 [[ 38 241]]

 [[ 41 244]]

 [[ 46 245]]

 [[ 48 244]]

 [[ 50 242]]

 [[ 55 244]]

 [[ 53 249]]

 [[ 53 257]]

 [[ 56 264]]

 [[ 57 266]]

 [[ 62 271]]

 [[ 64 271]]

 [[ 67 274]]

 [[ 68 276]]

 [[ 70 281]]

 [[ 71 285]]

 [[ 72 291]]

 [[ 74 289]]

 [[ 77 284]]

 [[ 81 275]]

 [[ 81 272]]

 [[ 84 267]]

 [[ 86 262]]

 [[ 86

[[[162 110]]

 [[157 112]]

 [[147 113]]

 [[142 114]]

 [[126 118]]

 [[119 120]]

 [[109 123]]

 [[ 97 127]]

 [[ 92 130]]

 [[ 89 131]]

 [[ 83 132]]

 [[ 77 134]]

 [[ 72 137]]

 [[ 61 141]]

 [[ 53 144]]

 [[ 42 148]]

 [[ 39 149]]

 [[ 36 150]]

 [[ 32 151]]

 [[ 28 152]]

 [[ 14 153]]

 [[  8 154]]

 [[  5 155]]

 [[  3 156]]

 [[  2 159]]

 [[  0 162]]

 [[  1 185]]

 [[  7 186]]

 [[  7 188]]

 [[  8 190]]

 [[  5 193]]

 [[  5 196]]

 [[  6 198]]

 [[  9 200]]

 [[ 13 202]]

 [[ 18 207]]

 [[ 22 210]]

 [[ 24 211]]

 [[ 26 212]]

 [[ 29 212]]

 [[ 34 217]]

 [[ 36 219]]

 [[ 37 221]]

 [[ 36 225]]

 [[ 34 227]]

 [[ 32 228]]

 [[ 33 231]]

 [[ 32 240]]

 [[ 35 243]]

 [[ 36 245]]

 [[ 38 251]]

 [[ 41 257]]

 [[ 46 264]]

 [[ 48 265]]

 [[ 52 265]]

 [[ 52 262]]

 [[ 54 260]]

 [[ 57 261]]

 [[ 58 263]]

 [[ 58 265]]

 [[ 59 267]]

 [[ 56 270]]

 [[ 56 275]]

 [[ 57 276]]

 [[ 57 282]]

 [[ 59 285]]

 [[ 59 293]]

 [[ 61 293]]

 [[ 62 291]]

 [[ 62 287]]

 [[ 67 283]]

 [[ 69

[[[157 111]]

 [[150 114]]

 [[144 115]]

 [[139 115]]

 [[134 116]]

 [[130 117]]

 [[123 119]]

 [[120 121]]

 [[117 122]]

 [[110 123]]

 [[107 125]]

 [[104 125]]

 [[ 93 130]]

 [[ 90 131]]

 [[ 84 132]]

 [[ 81 133]]

 [[ 74 136]]

 [[ 61 142]]

 [[ 49 146]]

 [[ 35 151]]

 [[ 32 152]]

 [[ 29 153]]

 [[ 22 155]]

 [[ 18 156]]

 [[ 13 156]]

 [[  8 157]]

 [[  5 159]]

 [[  2 160]]

 [[  0 160]]

 [[  0 186]]

 [[  3 189]]

 [[  4 192]]

 [[  3 194]]

 [[  2 195]]

 [[  1 195]]

 [[  1 201]]

 [[  6 202]]

 [[ 13 209]]

 [[ 16 210]]

 [[ 19 212]]

 [[ 22 216]]

 [[ 20 218]]

 [[ 16 220]]

 [[ 17 222]]

 [[ 21 226]]

 [[ 23 229]]

 [[ 24 231]]

 [[ 25 235]]

 [[ 27 237]]

 [[ 32 240]]

 [[ 34 241]]

 [[ 39 240]]

 [[ 39 238]]

 [[ 37 236]]

 [[ 38 233]]

 [[ 41 233]]

 [[ 43 235]]

 [[ 44 235]]

 [[ 45 236]]

 [[ 46 237]]

 [[ 48 240]]

 [[ 47 244]]

 [[ 45 242]]

 [[ 41 246]]

 [[ 41 250]]

 [[ 42 254]]

 [[ 43 256]]

 [[ 46 258]]

 [[ 50 261]]

 [[ 53 262]]

 [[ 55 264]]

 [[ 55

[[[161 111]]

 [[156 112]]

 [[152 113]]

 [[148 115]]

 [[143 116]]

 [[134 117]]

 [[130 118]]

 [[126 119]]

 [[109 124]]

 [[ 96 128]]

 [[ 90 131]]

 [[ 87 131]]

 [[ 84 132]]

 [[ 81 133]]

 [[ 59 142]]

 [[ 39 148]]

 [[ 28 153]]

 [[ 19 156]]

 [[ 13 157]]

 [[  8 157]]

 [[  3 158]]

 [[  2 159]]

 [[  0 159]]

 [[  0 199]]

 [[  6 206]]

 [[ 11 210]]

 [[ 13 212]]

 [[ 14 214]]

 [[ 15 216]]

 [[ 15 224]]

 [[ 16 227]]

 [[ 17 229]]

 [[ 18 231]]

 [[ 22 232]]

 [[ 22 230]]

 [[ 20 226]]

 [[ 22 224]]

 [[ 26 224]]

 [[ 28 226]]

 [[ 29 228]]

 [[ 30 231]]

 [[ 30 234]]

 [[ 28 237]]

 [[ 32 240]]

 [[ 31 247]]

 [[ 31 250]]

 [[ 32 254]]

 [[ 34 257]]

 [[ 36 259]]

 [[ 40 263]]

 [[ 43 263]]

 [[ 45 261]]

 [[ 46 257]]

 [[ 50 259]]

 [[ 52 261]]

 [[ 54 264]]

 [[ 55 266]]

 [[ 55 275]]

 [[ 58 278]]

 [[ 58 282]]

 [[ 56 284]]

 [[ 54 285]]

 [[ 55 287]]

 [[ 57 289]]

 [[ 60 290]]

 [[ 62 290]]

 [[ 64 289]]

 [[ 66 287]]

 [[ 67 285]]

 [[ 68 283]]

 [[ 73 272]]

 [[ 75

In [5]:
len(list)

48

In [6]:
x = set(list)

In [7]:
len(x)

20